apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Release.Name }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: machine-manager

  template:
    metadata:
      labels:
        app: machine-manager

    spec:
      containers:
        - name: machine-manager

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.containerPort }}

          volumeMounts:
            - name: machine-storage
              mountPath: /configs

      volumes:
        - name: machine-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc
