apiVersion: v1
kind: Service

metadata:
  name: {{ .Release.Name }}

spec:
  type: {{ .Values.service.type }}

  selector:
    app: machine-manager

  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      nodePort: {{ .Values.service.nodePort }}
