replicaCount: 1

image:
  repository: machine-manager
  tag: "1.0"
  pullPolicy: Never

service:
  type: ClusterIP
  port: 5001
  #nodePort: 30001

containerPort: 5001

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 1Gi
